package ca.pranavpatel.algo.gridpointcode;

// Generated by screening/expand.py. Do not edit.
//
// The advisory word list of SPEC.md section 17, as hashes. The words
// themselves are not in this repository. Hashing keeps them out of it;
// it is not a security measure, and section 17.1 says so.

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

final class ScreenList {

    static final String VERSION = "2026.1";

    private static final String PACKED = ""
            + "0e750da63138992731cb989237191c123c3333744ae6781a"
            + "4d8e9476554f82335dcf99826179ddef7fec0b7081f3e90d"
            + "864fbc7e86c85cc98c287c5b91a8af4aa4c8907cab5ad874"
            + "ac2f65ceae26f21fb469b606b83a8d09b9e18f4dbb9666e8"
            + "c0456601c209b342c67e1cc5da8e5c48db1214deeaf99aa3"
            + "ee2fab80ee3cf8a0f933439afa2f162ffb5c1aee";

    static final Set<String> ENTRIES = unpack();

    private ScreenList() {
    }

    private static Set<String> unpack() {
        Set<String> entries = new HashSet<>();
        for (int i = 0; i < PACKED.length(); i += 8) {
            entries.add(PACKED.substring(i, i + 8));
        }
        return Collections.unmodifiableSet(entries);
    }
}
