// The places the site opens on, and the places it has a page for.
//
// Build-time only. The file behind this is most of half a megabyte, so nothing
// that runs in a browser imports it: a page gets the one country it needs from
// /places/<ISO>.json, and lib/country.ts is the browser's side of that.
//
// The data is generated by scripts/build-places.mjs, which explains what is in
// it and why. What this module adds is the part every consumer would otherwise
// repeat: how a place is described, which places a country's visitors are
// shown, and a check that fails the build if the file stops being true.

import { GPC } from '@pranavpatel.ca/algo-gridpointcode';

import data from '../data/places.json';

export interface Place {
    /**
     * `featured`: a market or old quarter, what a country's visitors are shown.
     * `sight`: famous, with no address at all, and a page but never shown first.
     * `city`: a capital or large city.
     */
    kind: 'featured' | 'sight' | 'city';
    /** ISO 3166-1 alpha-2, as a visitor's connection reports it. */
    iso: string;
    name: string;
    region: string | null;
    /** The city it is in, as someone giving directions there would say. */
    city: string | null;
    /** A town within 60 km, for a sight out of town. */
    near: string | null;
    lat: number;
    lon: number;
    country: string;
    /** `country/place`, the address of its page under /play. */
    slug: string;
    description?: string | null;
    wikipedia?: string;
    wikidata?: string;
    population?: number;
    capital?: boolean;
}

export const PLACES = data.places as Place[];

export const COUNTRIES = data.countries as Record<string, { name: string; slug: string }>;

export const ZONES = data.zones as Record<string, string>;

/**
 * Where a visitor is taken when their country cannot be told.
 *
 * Egypt, for Khan el-Khalili: a souq known far beyond Cairo, whose lanes and
 * stalls are found the way the format is for, by landmark and not by number.
 */
export const DEFAULT_COUNTRY = 'EG';

/**
 * "Manek Chowk, Ahmedabad, Gujarat, India", skipping whatever is not known and
 * whatever repeats: Singapore is not "Singapore, Singapore".
 */
export function where(place: Place): string {
    const parts = [place.name, place.city, place.region, place.country].filter(Boolean) as string[];
    return parts.filter((part, at) => part !== parts[at - 1]).join(', ');
}

/**
 * The address people use for it today: "Manek Chowk, Ahmedabad".
 *
 * A name and a city, which is what a market is called by the people who go
 * there, and all it is called. Everything finer is directions.
 */
export function spoken(place: Place): string {
    return place.city ? `${place.name}, ${place.city}` : place.name;
}

/**
 * What a country's visitors are shown first, best first.
 *
 * Its featured places in the order they were chosen: markets and old quarters,
 * where doors have no address of their own. A country with none gets its
 * capital, which is still somewhere in their own country, rather than a market
 * on another continent.
 */
export function shownFor(iso: string): Place[] {
    const featured = PLACES.filter((p) => p.iso === iso && p.kind === 'featured');
    if (featured.length) return featured;
    const capital = PLACES.find((p) => p.iso === iso && p.capital);
    return capital ? [capital] : [];
}

const ORDER: Record<Place['kind'], number> = { featured: 0, city: 1, sight: 2 };

/** Other places in the same country, for a page to link to: markets first. */
export function neighboursOf(place: Place, most = 12): Place[] {
    return PLACES
        .filter((p) => p.iso === place.iso && p.slug !== place.slug)
        .sort((a, b) =>
            ORDER[a.kind] - ORDER[b.kind]
            || (b.population ?? 0) - (a.population ?? 0))
        .slice(0, most);
}

/**
 * Dashes, curly quotes and invisible spaces. Place names come from sources that
 * set them typographically; the generator writes them plainly, and this is what
 * holds it to that.
 */
const TYPOGRAPHIC = /[\u2013\u2014\u2018\u2019\u201C\u201D\u00A0\u200B-\u200D\uFEFF]/;

/**
 * Fails the build if the file stops being true.
 *
 * A generated file that has been edited by hand, or regenerated by a script
 * that has since changed, is the kind of fault that ships and is found by a
 * reader. The same promise checkSamples makes for the specification's examples.
 */
export function checkPlaces(): void {
    const seen = new Set<string>();
    for (const p of PLACES) {
        if (seen.has(p.slug)) throw new Error(`two places at /play/${p.slug}`);
        seen.add(p.slug);
        if (!/^[a-z0-9-]+\/[a-z0-9-]+$/.test(p.slug)) throw new Error(`bad address: ${p.slug}`);
        if (!(Math.abs(p.lat) <= 90 && Math.abs(p.lon) <= 180)) throw new Error(`${p.slug} is off the planet`);
        if (!COUNTRIES[p.iso]) throw new Error(`${p.slug} names an unknown country ${p.iso}`);
        for (const text of [p.name, p.region, p.city, p.near, p.description, p.country, p.wikipedia]) {
            if (text && TYPOGRAPHIC.test(text)) {
                throw new Error(`${p.slug} carries typographic punctuation: ${text}`);
            }
        }
        GPC.encode(p.lat, p.lon);
    }
    if (!shownFor(DEFAULT_COUNTRY).length) {
        throw new Error(`the default country ${DEFAULT_COUNTRY} has nothing to show`);
    }
}
