#  Copyright 2026 Pranavkumar Patel
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Generated by screening/expand.py. Do not edit.
#
# The advisory word list of SPEC.md section 17, as 32-bit FNV-1a
# hashes. The words themselves are not in this repository. Hashing
# keeps them out of it; it is not a security measure, and section
# 17.1 says so.

VERSION = "2026.1"

_PACKED = (
    "091a21210c99406e11d8522415e33f40194826ea1e3225bb"
    "1e75e3a51f2c744e238d033127f3a33e2e7026f9408d30d8"
    "4bd57b15526fcc485559ef785b7931fd5d7a67ac5dee0df3"
    "68d5a8bc6b99d5fb72b0d782785a26918236485983cdd187"
    "8a3d159f94c12502a924d54bb33a58e9b95f7094ba9445fc"
    "cb0e5110d3c2a92ad81a9b47db1842ffee0e8829"
)

ENTRIES = frozenset(_PACKED[i:i + 8] for i in range(0, len(_PACKED), 8))
