#  Copyright 2026 Pranavkumar Patel
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Generated by screening/expand.py. Do not edit.
#
# The advisory word list of SPEC.md section 17, as hashes. The words
# themselves are not in this repository. Hashing keeps them out of it;
# it is not a security measure, and section 17.1 says so.

VERSION = "2026.1"

_PACKED = (
    "0e750da63138992731cb989237191c123c3333744ae6781a"
    "4d8e9476554f82335dcf99826179ddef7fec0b7081f3e90d"
    "864fbc7e86c85cc98c287c5b91a8af4aa4c8907cab5ad874"
    "ac2f65ceae26f21fb469b606b83a8d09b9e18f4dbb9666e8"
    "c0456601c209b342c67e1cc5da8e5c48db1214deeaf99aa3"
    "ee2fab80ee3cf8a0f933439afa2f162ffb5c1aee"
)

ENTRIES = frozenset(_PACKED[i:i + 8] for i in range(0, len(_PACKED), 8))
