#  Copyright 2026 Pranavkumar Patel
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""Expands the advisory word list into the hashed form the ports carry.

    python screening/expand.py

Reads `screening/words.txt`, which is not in this repository and never will
be. Writes one generated source file per port, each holding the version tag
from `screening/VERSION` and the sorted hashes of every variant.

The rules are specification section 17. The expansion itself lives in
`reference/gpc2.py`, so there is one implementation of it and this script is
only plumbing.

Nothing here runs in CI, because CI has no word file. What CI checks instead is
that the four ports agree: each asserts the version, the count and the digest
recorded in `test_data/v2_screen_list.csv`, so a port whose copy drifted fails.
"""

import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "reference"))

import gpc2  # noqa: E402

WORDS = HERE / "words.txt"
VERSION = HERE / "VERSION"

# Each port states its copyright the way that port already does: the full
# licence in Python and C#, two lines in TypeScript, and none in Java, whose
# files carry only the package declaration.
APACHE = ("Copyright 2026 Pranavkumar Patel",
          "",
          "Licensed under the Apache License, Version 2.0 (the \"License\");",
          "you may not use this file except in compliance with the License.",
          "You may obtain a copy of the License at",
          "",
          "    http://www.apache.org/licenses/LICENSE-2.0",
          "",
          "Unless required by applicable law or agreed to in writing, software",
          "distributed under the License is distributed on an \"AS IS\" BASIS,",
          "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
          "See the License for the specific language governing permissions and",
          "limitations under the License.")

HEADER = ("Generated by screening/expand.py. Do not edit.",
          "",
          "The advisory word list of SPEC.md section 17, as 32-bit FNV-1a",
          "hashes. The words themselves are not in this repository. Hashing",
          "keeps them out of it; it is not a security measure, and section",
          "17.1 says so.")


def load():
    """The version tag and every variant, sorted and deduplicated."""
    if not WORDS.exists():
        raise SystemExit(
            "screening/words.txt is missing. It is deliberately not in the\n"
            "repository; see screening/README.md for what it holds.")

    version = VERSION.read_text(encoding="utf-8").strip()
    if not version:
        raise SystemExit("screening/VERSION is empty.")

    variants = set()
    dropped = []
    for line in WORDS.read_text(encoding="utf-8").splitlines():
        word = line.strip().lower()
        if not word or word.startswith("#"):
            continue
        expanded = gpc2.expand_word(word)
        if not expanded:
            dropped.append(word)
            continue
        variants.update(expanded)

    entries = sorted(gpc2.screen_hash(v) for v in variants)
    return version, entries, len(variants), dropped


def digest(entries):
    """The SHA-256 of the entries joined by LF. Pinned in the vectors.

    This one is a real hash because it identifies the list rather than hiding
    it, and it is computed here and in the four test suites -- all of which
    already have SHA-256 to hand for the wide sample. No port's library code
    needs it; section 17.3 is what the ports themselves compute."""
    return hashlib.sha256("\n".join(entries).encode("utf-8")).hexdigest()


def chunks(entries, per_line):
    for i in range(0, len(entries), per_line):
        yield "".join(entries[i:i + per_line])


def comment(prefix, lines=HEADER):
    return "\n".join((prefix + " " + line).rstrip() for line in lines)


def write(path, text):
    path.write_text(text, encoding="utf-8", newline="\n")
    print("  %s" % path.relative_to(REPO).as_posix())


def python_port(version, entries):
    body = "\n".join('    "%s"' % chunk for chunk in chunks(entries, 6))
    return '''%s

%s

VERSION = "%s"

_PACKED = (
%s
)

ENTRIES = frozenset(_PACKED[i:i + 8] for i in range(0, len(_PACKED), 8))
''' % (comment("# ", APACHE), comment("#"), version, body)


def typescript_port(version, entries):
    body = "\n".join("    '%s' +" % chunk for chunk in chunks(entries, 6))
    return '''// Copyright 2026 Pranavkumar Patel
// Licensed under the Apache License, Version 2.0

%s

export const VERSION = '%s';

const PACKED =
%s
    '';

export const ENTRIES: ReadonlySet<string> = (() => {
    const entries = new Set<string>();
    for (let i = 0; i < PACKED.length; i += 8) {
        entries.add(PACKED.substring(i, i + 8));
    }
    return entries;
})();
''' % (comment("//"), version, body)


def csharp_port(version, entries):
    body = "\n".join('            + "%s"' % chunk for chunk in chunks(entries, 6))
    return '''%s

%s

using System.Collections.Generic;

namespace Ca.Pranavpatel.Algo.GridPointCode {

    internal static class ScreenList {

        internal const string Version = "%s";

        private const string Packed = ""
%s;

        internal static readonly HashSet<string> Entries = Unpack();

        private static HashSet<string> Unpack() {
            HashSet<string> entries = [];
            for (int i = 0; i < Packed.Length; i += 8) {
                _ = entries.Add(Packed.Substring(i, 8));
            }
            return entries;
        }
    }
}
''' % (comment("// ", APACHE), comment("//"), version, body)


def java_port(version, entries):
    body = "\n".join('            + "%s"' % chunk for chunk in chunks(entries, 6))
    return '''package ca.pranavpatel.algo.gridpointcode;

%s

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

final class ScreenList {

    static final String VERSION = "%s";

    private static final String PACKED = ""
%s;

    static final Set<String> ENTRIES = unpack();

    private ScreenList() {
    }

    private static Set<String> unpack() {
        Set<String> entries = new HashSet<>();
        for (int i = 0; i < PACKED.length(); i += 8) {
            entries.add(PACKED.substring(i, i + 8));
        }
        return Collections.unmodifiableSet(entries);
    }
}
''' % (comment("//"), version, body)


def main():
    version, entries, variants, dropped = load()

    print("list %s: %d variants, %d distinct hashes, digest %s"
          % (version, variants, len(entries), digest(entries)[:16]))
    if dropped:
        print("%d words cannot appear in a code at all and were dropped"
              % len(dropped))

    write(REPO / "python" / "src" / "gridpointcode_algo_pranavpatel_ca"
          / "screen_list.py", python_port(version, entries))
    write(REPO / "typescript" / "src" / "ScreenList.ts",
          typescript_port(version, entries))
    write(REPO / "csharp" / "gpc" / "ScreenList.cs",
          csharp_port(version, entries))
    write(REPO / "java" / "src" / "main" / "java" / "ca" / "pranavpatel"
          / "algo" / "gridpointcode" / "ScreenList.java",
          java_port(version, entries))

    print("\nRun `python test_data/generate.py` next: the screening vectors are"
          "\nbuilt from this list and will have moved.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
